name: Package Application with Pyinstaller

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Package Application
      uses: JackMcKew/pyinstaller-action-linux@main
      with:
        path: vrpc --icon=favicon.ico --name="ValoRPC" --noconsole --noconfirm --add-data "info.json;." --add-data "Tesseract-OCR;Tesseract-OCR" --add-data "favicon.ico;." --add-data "ValoRPC Web Downloader.exe;."

    - uses: actions/upload-artifact@v2
      with:
        name: name-of-artifact
        path: /dist/update_ifp_f.py
