name: Package Application with Pyinstaller

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Test Build Python Exe
      uses: eric2788/pyinstaller-build@master
      with:
        main: vrpc
        artifact: Program
        use-dependencies: false
    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: python_exe
        path: dist
